/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'
import { Route as ComicComicSlugImport } from './routes/comic.$comicSlug'

// Create Virtual Routes

const ComicComicSlugChapterChapterIdLazyImport = createFileRoute(
  '/comic/$comicSlug/chapter/$chapterId',
)()

// Create/Update Routes

const ExploreRoute = ExploreImport.update({
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComicComicSlugRoute = ComicComicSlugImport.update({
  path: '/comic/$comicSlug',
  getParentRoute: () => rootRoute,
} as any)

const ComicComicSlugChapterChapterIdLazyRoute =
  ComicComicSlugChapterChapterIdLazyImport.update({
    path: '/comic/$comicSlug/chapter/$chapterId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/comic_.$comicSlug.chapter.$chapterId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/comic/$comicSlug': {
      preLoaderRoute: typeof ComicComicSlugImport
      parentRoute: typeof rootRoute
    }
    '/comic/$comicSlug/chapter/$chapterId': {
      preLoaderRoute: typeof ComicComicSlugChapterChapterIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExploreRoute,
  ComicComicSlugRoute,
  ComicComicSlugChapterChapterIdLazyRoute,
])

/* prettier-ignore-end */
