/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'
import { Route as ReadComicSlugImport } from './routes/read.$comicSlug'

// Create/Update Routes

const ExploreRoute = ExploreImport.update({
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReadComicSlugRoute = ReadComicSlugImport.update({
  path: '/read/$comicSlug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/read/$comicSlug': {
      preLoaderRoute: typeof ReadComicSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExploreRoute,
  ReadComicSlugRoute,
])

/* prettier-ignore-end */
